Repository Sharp-as-a-tech/chat-application, pull requests merged in 2022-06, with the labels that each got.

#15 some changes were done
  src/main/java/com/example/demo/AdminChatServlet.java
  src/main/java/com/example/demo/Adminchatservlet.java
  src/main/java/com/example/demo/ChRoomServlet.java
  src/main/java/com/example/demo/UPLOADSERVLET.java
  src/main/webapp/ADD USER.jsp
  src/main/webapp/LOGIN.jsp
Labels: help wanted

#18 Added a comment to AdminChatServlet class
  src/main/java/com/example/demo/AdminChatServlet.java
Labels: documentation

#29 README.md updated
  README.md
Labels: enhancement

#34 some changes were added to adminservlet
  src/main/java/com/example/demo/AdminChatServlet.java
Labels: enhancement

#36 some change were done
  src/main/webapp/LOGIN.jsp
Labels: enhancement

#39 Typos error solved
  README.md
Labels: enhancement
